name: Convert Markdown to EPUB

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive texlive-latex-extra

    - name: Convert to EPUB2
      run: |
        pandoc full_book.md -o full_book.epub2 --to epub2

    - name: Convert to EPUB3
      run: |
        pandoc full_book.md -o full_book.epub3 --to epub3

    - name: Convert to EPUB3 with GladTeX
      run: |
        sudo apt-get install -y gladtex
        pandoc full_book.md -o full_book_gladtex.epub3 --to epub3 --gladtex

    - name: Upload EPUB2
      uses: actions/upload-artifact@v3
      with:
        name: full_book_epub2
        path: full_book.epub2

    - name: Upload EPUB3
      uses: actions/upload-artifact@v3
      with:
        name: full_book_epub3
        path: full_book.epub3

    - name: Upload EPUB3 with GladTeX
      uses: actions/upload-artifact@v3
      with:
        name: full_book_epub3_gladtex
        path: full_book_gladtex.epub3
