name: Convert Markdown to EPUB

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Pandoc, LaTeX, and Python
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive texlive-latex-extra gladtex python3-pip

    - name: Preprocess Markdown
      run: |
        python3 preprocess_markdown_for_ebook.py

    - name: Convert to EPUB2
      run: |
        pandoc full_book_preprocessed.md -o full_book_epub2.epub --to epub2

    - name: Convert to EPUB3
      run: |
        pandoc full_book_preprocessed.md -o full_book_epub3.epub --to epub3

    - name: Convert to EPUB3 with GladTeX
      run: |
        pandoc full_book_preprocessed.md -o full_book_epub3_gladtex.epub --to epub3 --gladtex

    - name: Upload EPUB2
      uses: actions/upload-artifact@v3
      with:
        name: full_book_epub2
        path: full_book_epub2.epub

    - name: Upload EPUB3
      uses: actions/upload-artifact@v3
      with:
        name: full_book_epub3
        path: full_book_epub3.epub

    - name: Upload EPUB3 with GladTeX
      uses: actions/upload-artifact@v3
      with:
        name: full_book_epub3_gladtex
        path: full_book_epub3_gladtex.epub
