name: Convert Markdown to EPUB

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Pandoc and LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive texlive-latex-extra gladtex

    - name: Preprocess Markdown
      run: |
        # Remove HTML comments from the Markdown file
        sed '/<!--/,/-->/d' full_book.md > full_book_preprocessed.md

    - name: Convert to EPUB2
      run: |
        pandoc full_book_preprocessed.md -o full_book_epub2.epub --to epub2 --webtex=https://latex.codecogs.com/svg.latex? --resource-path=static

    - name: Convert to EPUB3
      run: |
        pandoc full_book_preprocessed.md -o full_book_epub3.epub --to epub3 --webtex=https://latex.codecogs.com/svg.latex? --resource-path=static

    - name: Convert to EPUB3 with GladTeX
      run: |
        pandoc full_book_preprocessed.md -o full_book_epub3_gladtex.epub --to epub3 --gladtex --resource-path=static

    - name: Upload EPUB2
      uses: actions/upload-artifact@v3
      with:
        name: full_book_epub2
        path: full_book_epub2.epub

    - name: Upload EPUB3
      uses: actions/upload-artifact@v3
      with:
        name: full_book_epub3
        path: full_book_epub3.epub

    - name: Upload EPUB3 with GladTeX
      uses: actions/upload-artifact@v3
      with:
        name: full_book_epub3_gladtex
        path: full_book_epub3_gladtex.epub
