name: Convert Markdown to EPUB

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Pandoc, LaTeX, and Python
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive texlive-latex-extra gladtex python3-pip

    - name: Preprocess Markdown
      run: |
        python3 preprocess_markdown_for_ebook.py

    - name: Convert to EPUB3
      run: |
        pandoc full_book_preprocessed.md -o nanosystems.epub --to epub3

    - name: Upload EPUB3
      uses: actions/upload-artifact@v4
      with:
        name: nanosystems_epub
        path: nanosystems.epub
